using Microsoft.EntityFrameworkCore.Migrations;

namespace CYouEcommerce.Migrations
{
    public partial class seedDatabase : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("insert into CPUs ([name], price, brand, model, series, details) values ('AMD Ryzen 7 2700X', 279.99, 'AMD', 'YD270XBGAFBOX', 'Ryzen 7 Series', '2nd Gen Ryzen. AMD StoreMI Technology. AMD SenseMI Technology. AMD Ryzen Master Utility. Socket AM4. Max Boost Frequency 4.3 GHz. DDR4 Support. Thermal Design Power 105W')");
            migrationBuilder.Sql("insert into CPUs ([name], price, brand, model, series, details) values ('Intel Core i5-8400', 224.99, 'Intel', 'BX80684I58400', 'Core i5 8th Gen Series', 'Only Compatible with Intel 300 Series Motherboard. For A Great VR Experience. Max Turbo Frequency 4.0 GHz. Intel UHD Graphics 630. DDR4 Support. Socket LGA 1151 (300 Series)')");
            migrationBuilder.Sql("insert into CPUs ([name], price, brand, model, series, details) values ('AMD Ryzen 5 2400G', 159.99, 'AMD', 'YD2400C5FBBOX', 'Ryzen 5 Series', 'Built-In Radeon Vega RX 11 Graphics. 4 Cores / 8 Threads Unlocked. Frequency: 3.9 GHz. Max Boost. Socket Type: AM4. 6MB total cache')");
            migrationBuilder.Sql("insert into CPUs ([name], price, brand, model, series, details) values ('AMD RYZEN 3 2200G', 99.99, 'Ryzen 3', 'YD2200C5FBBOX', 'Ryzen 3 Series', 'Built-In Radeon Vega 8 Graphics. 4 Cores Unlocked. Frequency: 3.7 GHz Max Boost. Socket Type: AM4. 6MB Total Cache')");
            migrationBuilder.Sql("insert into CPUs ([name], price, brand, model, series, details) values ('Intel Core i5-8600K', 279.99, 'Intel', 'BX80684I58600K', 'Core i5 8th Gen Series', 'Only Compatible with Intel 300 Series Motherboard. For A Great VR Experience. Max Turbo Frequency 4.3 GHz. Intel UHD Graphics 630. Unlocked Processor. DDR4 Support. Socket LGA 1151')");
            migrationBuilder.Sql("insert into CPUs ([name], price, brand, model, series, details) values ('Intel Core i7-8700K', 379.99, 'Intel', 'BX80684I78700K', 'Core i7 8th Gen Series', 'Only Compatible with Intel 300 Series Motherboard. For A Great VR Experience. Max Turbo Frequency 4.7 GHz. Intel UHD Graphics 630. Unlocked Processor. DDR4 Support. Socket LGA 1151')");

            migrationBuilder.Sql("insert into Motherboards ([name], price, brand, model, series, details) values ('MSI H310-A PRO', 74.99, 'MSI', 'H310-A PRO', '300 Series', 'Intel H310. 8th Generation Intel Core Processors. * Not backward compatible with older generation of LGA 1151 CPUs')");
            migrationBuilder.Sql("insert into Motherboards ([name], price, brand, model, series, details) values ('ASRock H370M Pro4', 79.99, 'ASRock', 'H370M Pro4', '300 Series', 'Intel H370. Supports 8th Generation Intel Core Processors (Socket 1151). * Not backward compatible with older generation of LGA 1151 CPUs. DDR4')");
            migrationBuilder.Sql("insert into Motherboards ([name], price, brand, model, series, details) values ('MSI X470 Gaming Plus', 119.99, 'MSI', 'X470 GAMING PLUS', '', 'AMD X470. Supports AMD Ryzen Desktop Processors and AMD A-Series/Athlon Processors for Socket AM4. Supports DDR4. A-series/ Athlon processors support up to 2400 MHz')");
            migrationBuilder.Sql("insert into Motherboards ([name], price, brand, model, series, details) values ('ASRockB450M-HDV', 192.76, 'ASRock', 'B450M-HDV', '', 'AMD B450. Ryzen Series. AMD Ryzen series CPUs (Pinnacle Ridge) support DDR4 3200+(OC)/ 2933/ 2667/ 2400/ 2133 ECC & non-ECC, un-buffered memory*. AMD Ryzen series CPUs. Support DDR4')");
            migrationBuilder.Sql("insert into Motherboards ([name], price, brand, model, series, details) values ('ASUS ROG Strix X470-I', 192.76, 'ASUS', 'Strix X470-I Gaming', 'ROG Series', 'AMD X470. AM4 socket for AMD Ryzen 2nd Generation/Ryzen with Radeon Vega Graphics/Ryzen 1st Generation/ 7th Generation A-Series/Athlon X4 Processors. AMD Ryzen 2nd Generation Processor. DDR4')");
            migrationBuilder.Sql("insert into Motherboards ([name], price, brand, model, series, details) values ('ASRockX299 Taichi', 246.99, 'ASRock', 'X399 Professional Gaming', 'Fatal1ty Series', 'AMD X399. Ryzen Threadripper Series. DDR4')");

            migrationBuilder.Sql("insert into RAMs ([name], price, brand, model, series, details) values ('HyperX Fury', 129.99, 'HyperX', 'HX421C14FBK2/8', 'FURY Series', '16GB (2 x 8GB) DDR4 2133MHz DRAM. Aluminum heat spreader. Intel XMP 2.0-ready (automatic overclocking). Optimized for Intel 100 series & X99. Supports AMD X370/B350/A320')");
            migrationBuilder.Sql("insert into RAMs ([name], price, brand, model, series, details) values ('HyperX Predator', 181.05, 'HyperX', 'HX430C15PB3K2/16', 'Predator Series', '16GB (2 x 8GB) DDR4 3000 RAM. Aluminum Heat Spreader. Intel XMP-ready. Plug N Play automatic overclocking. Optimized for Intel 100 Series & X99 chipset')");
            migrationBuilder.Sql("insert into RAMs ([name], price, brand, model, series, details) values ('CORSAIR Dominator Platinum', 183.99, 'CORSAIR', 'CMD16GX4M2B3000C15', 'Dominator Platinum Series', '16GB (2 x 8GB) 288-Pin DDR4 SDRAM DDR4 3000. Timing 15-17-17-35. CAS Latency 15. Voltage 1.35V')");
            migrationBuilder.Sql("insert into RAMs ([name], price, brand, model, series, details) values ('G.SKILL TridentZ RGB Series', 169.99, 'G.SKILL', 'F4-3200C16D-16GTZR', 'TridentZ RGB Series', '16GB (2 x 8GB) 288-Pin DDR4 SDRAM DDR4 3200. Timing 16-18-18-38. CAS Latency 16. Voltage 1.35V')");
            migrationBuilder.Sql("insert into RAMs ([name], price, brand, model, series, details) values ('CORSAIR Vengeance RGB Pro', 179.99, 'CORSAIR', 'CMW16GX4M2C3200C16W', 'Vengeance RGB Pro Series', '16GB (2 x 8GB) 288-Pin DDR4 DRAM DDR4 3200. Timing 16-18-18-36. CAS Latency 16. Voltage 1.35V')");
            migrationBuilder.Sql("insert into RAMs ([name], price, brand, model, series, details) values ('Patriot Viper LED', 271.56, 'Patriot', 'PVLW416G360C6K', 'Viper LED Series', '16GB (2 x 8GB) DDR4 3600MHz')");

            migrationBuilder.Sql("insert into Storages ([name], price, brand, model, series, details) values ('WD Blue', 49.99, 'Western Digital', 'WD10EZEX', 'Blue Series', '2TB 7200 RPM SATA 6Gb/s 64MB Cache 3.5 Inch')");
            migrationBuilder.Sql("insert into Storages ([name], price, brand, model, series, details) values ('WD Black', 99.99, 'Western Digital', 'WD1003FZEX', 'Black Series', '2TB 7200 RPM SATA 6Gb/s 64MB Cache 3.5 Inch')");
            migrationBuilder.Sql("insert into Storages ([name], price, brand, model, series, details) values ('Seagate BarraCuda', 79.99, 'Seagate', 'ST2000DM006', 'BarraCuda Series', '2TB 7200 RPM 64MB Cache SATA 6.0Gb/s 3.5')");
            migrationBuilder.Sql("insert into Storages ([name], price, brand, model, series, details) values ('Toshiba P300', 111.49, 'Toshiba', 'HDWD130XZSTA', 'P300 Series', '2TB 7200 RPM SATA 6Gb/s 64 MB Cache 3.5 inch')");
            migrationBuilder.Sql("insert into Storages ([name], price, brand, model, series, details) values ('Toshiba X300', 137.99, 'Toshiba', 'HDWE150XZSTA', 'X300 Series', '2TB 7200 RPM SATA 6Gb/s 128 MB Cache 3.5')");

            migrationBuilder.Sql("insert into GPUs ([name], price, brand, model, series, details) values ('MSI GeForce GTX 1060', 421.99, 'MSI', 'GeForce GTX 1060 GAMING 6G', '', '6GB 192-Bit GDDR5. Core Clock 1531 MHz. 1 x DL-DVI-D 1 x HDMI 2.0 3 x DisplayPort 1.4. PCI Express 3.0 x16')");
            migrationBuilder.Sql("insert into GPUs ([name], price, brand, model, series, details) values ('ASUS GeForce GTX 1060', 319.99, 'Asus', 'DUAL-GTX1060-O6G', '', '6GB 192-Bit GDDR5. Core Clock OC Mode: 1594 MHz. 1 x Native DVI-D 2 x Native HDMI 2.0 2 x Native DisplayPort 1.4. 1280 CUDA Cores. PCI Express 3.0')");
            migrationBuilder.Sql("insert into GPUs ([name], price, brand, model, series, details) values ('EVGA GeForce GTX 1050 SC GAMING', 139.99, 'EVGA', '03G-P4-6153-KR', '', '3GB 96-Bit GDDR5. Core Clock 1455 MHz. Boost Clock 1569 MHz. 1 x Dual-Link DVI-D 1 x HDMI 2.0b 1 x DisplayPort 1.4. 768 CUDA Cores. PCI Express 3.0')");
            migrationBuilder.Sql("insert into GPUs ([name], price, brand, model, series, details) values ('SAPPHIRE PULSE Radeon', 419.99, 'SAPPHIRE', '100420PSR', 'PULSE Series', '8GB 2048-Bit HBM2. Core Clock 1208 MHz. Boost Clock 1512 MHz. 1 x HDMI 2.0b 3 x DisplayPort 1.4. 3584 Stream Processors. PCI Express 3.0')");
            migrationBuilder.Sql("insert into GPUs ([name], price, brand, model, series, details) values ('MSI Radeon RX 580', 249.99, 'MSI', 'Radeon RX 580 8G V1', '', '8GB 256-Bit GDDR5. Boost Clock 1340 MHz. 1 x HDMI 2.0b 3 x DisplayPort 1.4. 2304 Stream Processors. PCI Express x16')");

            migrationBuilder.Sql("insert into PowerSupplys ([name], price, brand, model, series, details) values ('CORSAIR RMx Series RM550X', 99.99, 'CORSAIR', 'RM550x', 'RMx Series', 'ATX12V / EPS12V. Full Modular. 80 PLUS GOLD Certified. 100 - 240 V 47 - 63 Hz. +3.3V@25A, +5V@25A, +12V@45.8A, -12V@0.8A, +5VSB@3A')");
            migrationBuilder.Sql("insert into PowerSupplys ([name], price, brand, model, series, details) values ('BitFenix Formula 80 Plus', 59.31, 'BitFenix', 'BP-FM450ULAG-7R', 'Formula Gold Series', 'ATX 12V V2.4. 80 PLUS GOLD Certified. 100 - 240 V 47 - 63 Hz')");
            migrationBuilder.Sql("insert into PowerSupplys ([name], price, brand, model, series, details) values ('Seasonic Flagship PRIME 600', 199.99, 'SeaSonic', 'SSR-600TL', 'PRIME Series', 'Intel ATX 12 V. Full Modular. 80 PLUS TITANIUM Certified. 100 - 240 V 50/60 Hz. +3.3V@20A, +5V@20A, +12V@50A, -12V@0.3A, +5VSB@2.5A')");
            migrationBuilder.Sql("insert into PowerSupplys ([name], price, brand, model, series, details) values ('CORSAIR AX1600i', 377.99, 'CORSAIR', 'CP-9020087-NA', 'AX1600i Series', 'ATX. Full Modular. 80 PLUS TITANIUM Certified. 100 - 240 V 50/60 Hz. +5V@30A, +3.3V@30A, +12V@133.3A, -12V@0.8A, +5VSB@3.5A')");
            migrationBuilder.Sql("insert into PowerSupplys ([name], price, brand, model, series, details) values ('EVGA 500B', 38.96, 'EVGA', '100-B1-0500-KR', '500 B1 Series', 'ATX12V/EPS12V - Internal - 85% Efficiency - 500 W. 80 PLUS BRONZE Certified. 100 - 240 V 50/60 Hz')");

            migrationBuilder.Sql("insert into CoolingFans ([name], price, brand, model, series, details) values ('Dark Rock 4', 74.90, 'be quiet!', 'Dark Rock 4', 'Air Cooler Series', 'The be quiet! Dark Rock 4 CPU cooler with a virtually inaudible Silent Wings 135mm fan with an extremely high cooling performance (200W TDP) with 6 advanced technology 6mm copper heat pipe')");
            migrationBuilder.Sql("insert into CoolingFans ([name], price, brand, model, series, details) values ('Cooler Master MasterAir', 59.99, 'COOLER MASTER', 'MAM-T4PN-AFNPC-R1', 'MasterAir MA410M TUF Edition', 'Thermal Detection Senso. Air-Guide Armor. 28 Addressable RGB LED. Continuous Direct Contact Technology 2.0')");
            migrationBuilder.Sql("insert into CoolingFans ([name], price, brand, model, series, details) values ('Noctua NH-U14S', 64.99, 'Noctua', 'NH-U14S', '', '52mm slim design tailor-made for LGA2011. Premium quality quiet for 140mm fan')");
            migrationBuilder.Sql("insert into CoolingFans ([name], price, brand, model, series, details) values ('Corsair Hydro Series H100i PRO', 119.99, 'CORSAIR', 'CW-9060033-WW', 'Hydro Series H100i PRO RGB', 'Two ML120 PWM magnetic levitation fans. PWM fan-speed. Two ML120 PWM magnetic levitation fans.  PWM fan-speed control')");
            migrationBuilder.Sql("insert into CoolingFans ([name], price, brand, model, series, details) values ('NZXT Kraken X72', 199.00, 'NZXT', 'RL-KRX72-01', 'Kraken X72 Series', 'Includes Aer P radiator-optimized fan. Advanced lighting modes for a fully dynamic lighting experience. Reinforced, extended tubing for increased durability')");

            migrationBuilder.Sql("insert into Cases ([name], price, brand, model, series, details) values ('be quiet! Dark Base 700', 179.99, 'be quiet!', 'Dark Base', '700 Series', 'Invertable motherboard tray. Radiators up to 360mm on top, front and back. Tempered glass side panel. RGB LEDs controllable by motherboard or 6-color-switch')");
            migrationBuilder.Sql("insert into Cases ([name], price, brand, model, series, details) values ('Cougar Panzer EVO RGB', 219.99, 'COUGAR', 'Panzer Evo RGB', '', 'Four COUGAR Vortex RGB Fans Included, with 18 Addressable LEDs per Fan and 100 Lighting Effects. Four Tempered Glass Covers (Front/Top/Left/Right).Up to Four Double Slot 390mm Graphics Cards. Up to Eight Fans and Four Rater Cooling Radiators')");
            migrationBuilder.Sql("insert into Cases ([name], price, brand, model, series, details) values ('be quiet! Silent Base 601', 129.90, 'be quiet!', 'Silent Base', '600 Series', 'be quiet! Silent Base 601 Orange delivers the perfect combination of maximum silence and an excellent usability for remarkably quiet configurations')");
            migrationBuilder.Sql("insert into Cases ([name], price, brand, model, series, details) values ('Riotoro CR500 TG', 102.64, 'Riotoro', 'CR500', '', 'SPCC (Cold Roll Steel) Metal with Tempered Glass Window ATX Mid Tower. 1 x USB 3.0 / 2 x USB 2.0 / Audio Front Ports. 4 Internal 3.5 Drive Bays')");

            migrationBuilder.Sql("insert into accounts (name, address, email, phone, username, password) values ('chris', 'Address 1', 'chrisyoufacebook@gmail.com', 5555555555, 'cyou', 'password123')");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
